//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.17 at 07:16:44 PM MSK 
//


package moe.are.task.bean;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the moe.are.task.userservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: moe.are.task.userservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListAllUsersRequest }
     * 
     */
    public ListAllUsersRequest createListAllUsersRequest() {
        return new ListAllUsersRequest();
    }

    /**
     * Create an instance of {@link ListAllUsersResponse }
     * 
     */
    public ListAllUsersResponse createListAllUsersResponse() {
        return new ListAllUsersResponse();
    }

    /**
     * Create an instance of {@link ResponseBase }
     * 
     */
    public ResponseBase createResponseBase() {
        return new ResponseBase();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetUserByLoginRequest }
     * 
     */
    public GetUserByLoginRequest createGetUserByLoginRequest() {
        return new GetUserByLoginRequest();
    }

    /**
     * Create an instance of {@link GetUserByLoginResponse }
     * 
     */
    public GetUserByLoginResponse createGetUserByLoginResponse() {
        return new GetUserByLoginResponse();
    }

    /**
     * Create an instance of {@link UserDetails }
     * 
     */
    public UserDetails createUserDetails() {
        return new UserDetails();
    }

    /**
     * Create an instance of {@link RemoveUserByLoginRequest }
     * 
     */
    public RemoveUserByLoginRequest createRemoveUserByLoginRequest() {
        return new RemoveUserByLoginRequest();
    }

    /**
     * Create an instance of {@link RemoveUserByLoginResponse }
     * 
     */
    public RemoveUserByLoginResponse createRemoveUserByLoginResponse() {
        return new RemoveUserByLoginResponse();
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link UserDetailsWithAuth }
     * 
     */
    public UserDetailsWithAuth createUserDetailsWithAuth() {
        return new UserDetailsWithAuth();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUserByLoginRequest }
     * 
     */
    public UpdateUserByLoginRequest createUpdateUserByLoginRequest() {
        return new UpdateUserByLoginRequest();
    }

    /**
     * Create an instance of {@link UpdateUserByLoginResponse }
     * 
     */
    public UpdateUserByLoginResponse createUpdateUserByLoginResponse() {
        return new UpdateUserByLoginResponse();
    }

}
