//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.17 at 07:16:44 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://task.are.moe/UserService", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package moe.are.task.bean;
